version: "3.9"

services:
  timeline:
    build: .
    container_name: airtable-timeline
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
